### ISSUE TITLE
seq'ing a PersistentProtocolBufferMap yields only two of the four fields

### ISSUE THREAD

**Issue by jmibanez** [ninjudd/clojure-protobuf#39] opened 2013-01-04 11:58 UTC
Using the latest release of clojure-protobuf, and this particular .proto definition:

```
message Key {
  required bytes salt = 1;
  required bytes iv = 2;
  required bytes encryptedKey = 3;
  required bytes verifyingKey = 4;
}
```

When ever I try loading from a file via protobuf-load-stream or via protobuf-load, the returned protobuf object does not yield the encryptedKey and verifyingKey keys, and its str representation doesn't have those keys either, e.g.:

```
protobuf-raw-seq
-> {:salt #<ByteString com.google.protobuf.ByteString@ca222b04>, :iv #<ByteString com.google.protobuf.ByteString@ae9053d8>}

(:encryptedKey protobuf-raw-seq)
-> #<ByteString com.google.protobuf.ByteString@e2fd05ec>

(take 4 (seq protobuf-raw-seq))
-> ([:salt #<ByteString com.google.protobuf.ByteString@ca222b04>] [:iv #<ByteString com.google.protobuf.ByteString@ae9053d8>])
```

A function that I've written to unpack ByteStrings into byte arrays and translate the protobuf object into a Clojure map depends on being able to seq into the PersistentProtocolBufferMap without losing keys.

This is on Clojure 1.4.0

I can provide a minimal test case. I am not sure whether this is a bug in clojure-protobuf or protobuf itself, but doing (.. protobuf-raw-master-rec def type getFields) does yield the missing fields.

**Comment by eRaz0rHead** [comment] 2013-04-21 04:12
I believe this is the same error I discovered -- If I am correct, this is because of the mixedCase in the missing keys. 
If you were to check your schema you'd find that the keys are :encryptedkey  and not :encryptedKey.   

However, the actual value is stored with the camelCase key,  and so the toString() method is calling  .get( <all lower case> ) vs .get (<real key>)  , which returns null  and so it's left out of the output

**Comment by amalloy** [comment] 2013-04-22 20:05
Yes, this is a duplicate of #45: the default naming strategy doesn't work for mixedCase keys.

**Closed as completed by amalloy** 2013-04-22 20:05 UTC
